export const HTTP = {
  RESOURCE_CREATED: 201,
  OK: 200,
  ACCEPTED: 202,
  NO_CONTENT: 204,
  SERVER_ERROR: 500,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  CONFLICT: 409,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  GONE: 410,
  PRECONDITION_FAILED: 412,
  UNPROCESSABLE: 422,
};

export const PERSONALITIES = {
  INTROVERT: 'introvert',
  EXTROVERT: 'extrovert',
  PUBLIC_INTROVERT: 'public_introvert',
  PRIVATE_INTROVERT: 'private_introvert',
};
